title: Kacper Serewis
email: kacper@kacperserewis.net
description: >- # this means to ignore newlines until "baseurl:"
  Kacper's Portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kacperserewis.net" # the base hostname & protocol for your site, e.g. http://example.com

remote_theme: riggraz/no-style-please
# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page
sass:
  style: :compressed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
